version: '3'

services:
  
  worklearn:
    image: golden/meteor-dev
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/worklearndb

  mongo:
    image: mongo
    ports:
      - 27017:27017

  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - 1234:1234
