# Assistance From
# https://www.youtube.com/watch?v=Qw9zlE3t8Ko
# https://www.youtube.com/watch?v=0w0lJn4O6YQ

version: '3'

services:
  worklearn:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/worklearndb

  mongo:
    image: mongo
    ports:
      - 27017:27017

  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - 1234:1234
